
### register user
POST http://localhost:3900/api/users
Content-Type: application/json

{
    "name": "aniel",
    "email": "ar@cca.com",
    "password": "123456",
    "biz": true
}

### Authenticate user
POST http://localhost:3000/api/auth HTTP/1.1
Content-Type: application/json

{
    "email": "a@a.com",
    "password": "123456"
}

### autherization by header
GET  http://localhost:3000/api/users/me 
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEwMWMxMmU3NDUwYjBiM2ExYzA3YWUiLCJiaXoiOnRydWUsImlhdCI6MTU5NDg5NjYzOH0.esRDLtf01UNSSWtftU6GyP8ZtJUU2Er6XOd7X12tYfs

### autherization by query
POST http://localhost:3000/api/users/me?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEwMWMxMmU3NDUwYjBiM2ExYzA3YWUiLCJiaXoiOnRydWUsImlhdCI6MTU5NDg5NjYzOH0.esRDLtf01UNSSWtftU6GyP8ZtJUU2Er6XOd7X12tYfs


### Create card
POST http://localhost:3000/api/cards
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEwMWMxMmU3NDUwYjBiM2ExYzA3YWUiLCJiaXoiOnRydWUsImlhdCI6MTU5NDg5NjYzOH0.esRDLtf01UNSSWtftU6GyP8ZtJUU2Er6XOd7X12tYfs

{
    "bizName": "daniel ltd",
    "bizDescription": "work work work",
    "bizAddress": "TLV" ,
    "bizPhone": "0266666666"
}

### Get card
GET http://localhost:3000/api/cards/5f140d3092831823ea30d0da
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEwMWMxMmU3NDUwYjBiM2ExYzA3YWUiLCJiaXoiOnRydWUsImlhdCI6MTU5NDg5NjYzOH0.esRDLtf01UNSSWtftU6GyP8ZtJUU2Er6XOd7X12tYfs

### update card
PUT http://localhost:3000/api/cards/5f140d3092831823ea30d0da
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEwMWMxMmU3NDUwYjBiM2ExYzA3YWUiLCJiaXoiOnRydWUsImlhdCI6MTU5NDg5NjYzOH0.esRDLtf01UNSSWtftU6GyP8ZtJUU2Er6XOd7X12tYfs
Content-Type: application/json

{
    "bizName": "shaloms ltd",
    "bizDescription": "work work work",
    "bizAddress": "TLV" ,
    "bizPhone": "0266666666"
}

### delete card
DELETE  http://localhost:3000/api/cards/5f140d3092831823ea30d0da
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjEwMWMxMmU3NDUwYjBiM2ExYzA3YWUiLCJiaXoiOnRydWUsImlhdCI6MTU5NDg5NjYzOH0.esRDLtf01UNSSWtftU6GyP8ZtJUU2Er6XOd7X12tYfs